import { Spot, Hotel, Car } from './types';

export const INITIAL_SPOTS: Spot[] = [
  // Northern Areas & Gilgit-Baltistan
  { id: '1', name: 'Hunza Valley', region: 'Gilgit-Baltistan', description: 'Often called heaven on earth, known for its mountainous beauty and longevity of its people.', imageUrl: 'https://picsum.photos/id/1018/800/600', tags: ['nature', 'mountains', 'culture'], rating: 4.9, coordinates: { lat: 36.3167, lng: 74.6500 }, amenities: ['Hotels', 'Guides'], reviews: 120 },
  { id: '2', name: 'Attabad Lake', region: 'Gilgit-Baltistan', description: 'A turquoise lake created by a landslide in 2010, offering boating and jet skiing.', imageUrl: 'https://picsum.photos/id/1015/800/600', tags: ['lake', 'boating', 'adventure'], rating: 4.8, coordinates: { lat: 36.3537, lng: 74.8657 }, amenities: ['Boating', 'Snacks'], reviews: 95 },
  { id: '3', name: 'Baltit Fort', region: 'Gilgit-Baltistan', description: 'An ancient fort in the Hunza valley dating back to 700 years.', imageUrl: 'https://picsum.photos/id/1040/800/600', tags: ['history', 'culture'], rating: 4.7, coordinates: { lat: 36.3263, lng: 74.6706 }, amenities: ['Museum', 'Guided Tours'], reviews: 88 },
  { id: '4', name: 'Passu Cones', region: 'Gilgit-Baltistan', description: 'Iconic jagged peaks near the Passu Glacier.', imageUrl: 'https://picsum.photos/id/1036/800/600', tags: ['mountains', 'trekking', 'nature'], rating: 4.9, coordinates: { lat: 36.4789, lng: 74.8965 }, amenities: ['Viewpoint'], reviews: 150 },
  { id: '5', name: 'Skardu Valley', region: 'Gilgit-Baltistan', description: 'Gateway to K2 and home to cold deserts and lakes.', imageUrl: 'https://picsum.photos/id/1024/800/600', tags: ['adventure', 'mountains'], rating: 4.8, coordinates: { lat: 35.2989, lng: 75.6337 }, amenities: ['Airport', 'Hotels'], reviews: 110 },
  { id: '6', name: 'Deosai Plains', region: 'Gilgit-Baltistan', description: 'The second highest plateau in the world, known as the land of giants.', imageUrl: 'https://picsum.photos/id/1020/800/600', tags: ['nature', 'wildlife', 'camping'], rating: 4.9, coordinates: { lat: 35.0435, lng: 75.4328 }, amenities: ['Camping'], reviews: 130 },
  { id: '7', name: 'Shangrila Resort', region: 'Gilgit-Baltistan', description: 'Famous resort built around Lower Kachura Lake.', imageUrl: 'https://picsum.photos/id/1039/800/600', tags: ['luxury', 'lake', 'relax'], rating: 4.6, coordinates: { lat: 35.4260, lng: 75.4497 }, amenities: ['Resort', 'Boating'], reviews: 200 },
  { id: '8', name: 'Fairy Meadows', region: 'Gilgit-Baltistan', description: 'Grassland near one of the base camp sites of the Nanga Parbat.', imageUrl: 'https://picsum.photos/id/1043/800/600', tags: ['trekking', 'adventure', 'mountains'], rating: 4.9, coordinates: { lat: 35.3872, lng: 74.5778 }, amenities: ['Camping', 'Huts'], reviews: 180 },
  { id: '9', name: 'Naltar Valley', region: 'Gilgit-Baltistan', description: 'Known for its colorful lakes and ski resort.', imageUrl: 'https://picsum.photos/id/1016/800/600', tags: ['skiing', 'lakes', 'nature'], rating: 4.7, coordinates: { lat: 36.1368, lng: 74.1923 }, amenities: ['Skiing', 'Hotels'], reviews: 75 },
  { id: '10', name: 'Khunjerab Pass', region: 'Gilgit-Baltistan', description: 'Highest paved international border crossing in the world.', imageUrl: 'https://picsum.photos/id/1019/800/600', tags: ['adventure', 'border', 'high-altitude'], rating: 4.8, coordinates: { lat: 36.8490, lng: 75.4312 }, amenities: ['ATM'], reviews: 210 },
  { id: '11', name: 'Rakaposhi Viewpoint', region: 'Gilgit-Baltistan', description: 'Stunning roadside view of the Rakaposhi mountain.', imageUrl: 'https://picsum.photos/id/106/800/600', tags: ['viewpoint', 'food'], rating: 4.7, coordinates: { lat: 36.1952, lng: 74.4984 }, amenities: ['Restaurant'], reviews: 300 },
  { id: '12', name: 'Phander Lake', region: 'Gilgit-Baltistan', description: 'Known for trout fishing and crystal clear waters.', imageUrl: 'https://picsum.photos/id/111/800/600', tags: ['fishing', 'lake', 'peace'], rating: 4.8, coordinates: { lat: 36.1738, lng: 72.9304 }, amenities: ['Fishing'], reviews: 60 },
  
  // Khyber Pakhtunkhwa
  { id: '13', name: 'Naran Kaghan', region: 'Khyber Pakhtunkhwa', description: 'Popular tourist destination with river rafting and Saif-ul-Malook lake.', imageUrl: 'https://picsum.photos/id/124/800/600', tags: ['family', 'river', 'mountains'], rating: 4.5, coordinates: { lat: 34.9088, lng: 73.6502 }, amenities: ['Hotels', 'Rafting'], reviews: 400 },
  { id: '14', name: 'Lake Saif-ul-Malook', region: 'Khyber Pakhtunkhwa', description: 'A mountainous lake located at the northern end of the Kaghan Valley.', imageUrl: 'https://picsum.photos/id/128/800/600', tags: ['lake', 'mythology'], rating: 4.8, coordinates: { lat: 34.8732, lng: 73.6931 }, amenities: ['Boating', 'Horses'], reviews: 350 },
  { id: '15', name: 'Swat Valley', region: 'Khyber Pakhtunkhwa', description: 'Known as the Switzerland of the East.', imageUrl: 'https://picsum.photos/id/136/800/600', tags: ['nature', 'history'], rating: 4.6, coordinates: { lat: 35.2220, lng: 72.4258 }, amenities: ['Hotels', 'Shopping'], reviews: 250 },
  { id: '16', name: 'Malam Jabba', region: 'Khyber Pakhtunkhwa', description: 'Famous ski resort in Swat Valley.', imageUrl: 'https://picsum.photos/id/140/800/600', tags: ['skiing', 'adventure'], rating: 4.5, coordinates: { lat: 34.7990, lng: 72.5714 }, amenities: ['Chairlift', 'Skiing'], reviews: 180 },
  { id: '17', name: 'Kumrat Valley', region: 'Khyber Pakhtunkhwa', description: 'Lush green valley with thick forests.', imageUrl: 'https://picsum.photos/id/145/800/600', tags: ['forest', 'camping', 'nature'], rating: 4.7, coordinates: { lat: 35.5413, lng: 72.2132 }, amenities: ['Camping', 'Jeeps'], reviews: 120 },
  { id: '18', name: 'Chitral', region: 'Khyber Pakhtunkhwa', description: 'Known for the Kalash people and Tirich Mir mountain.', imageUrl: 'https://picsum.photos/id/15/800/600', tags: ['culture', 'mountains'], rating: 4.6, coordinates: { lat: 35.8510, lng: 71.7864 }, amenities: ['Hotels', 'Guides'], reviews: 90 },
  { id: '19', name: 'Kalash Valleys', region: 'Khyber Pakhtunkhwa', description: 'Home to the indigenous Kalash people with unique culture.', imageUrl: 'https://picsum.photos/id/160/800/600', tags: ['culture', 'festivals', 'history'], rating: 4.8, coordinates: { lat: 35.6644, lng: 71.6911 }, amenities: ['Homestays'], reviews: 110 },
  { id: '20', name: 'Shandur Top', region: 'Khyber Pakhtunkhwa', description: 'Highest polo ground in the world.', imageUrl: 'https://picsum.photos/id/164/800/600', tags: ['sports', 'high-altitude'], rating: 4.7, coordinates: { lat: 36.0772, lng: 72.5229 }, amenities: ['Camping'], reviews: 85 },
  { id: '21', name: 'Takht-i-Bahi', region: 'Khyber Pakhtunkhwa', description: 'Buddhist monastic complex dating to the 1st century BC.', imageUrl: 'https://picsum.photos/id/168/800/600', tags: ['history', 'archaeology'], rating: 4.6, coordinates: { lat: 34.3213, lng: 71.9442 }, amenities: ['Guide'], reviews: 70 },
  
  // Azad Kashmir
  { id: '22', name: 'Neelum Valley', region: 'Azad Kashmir', description: 'Bow-shaped valley with thick forests and rivers.', imageUrl: 'https://picsum.photos/id/175/800/600', tags: ['nature', 'rivers'], rating: 4.7, coordinates: { lat: 34.5861, lng: 73.9068 }, amenities: ['Hotels'], reviews: 220 },
  { id: '23', name: 'Ratti Gali Lake', region: 'Azad Kashmir', description: 'Alpine glacial lake famous for its red flowers.', imageUrl: 'https://picsum.photos/id/180/800/600', tags: ['trekking', 'lake'], rating: 4.9, coordinates: { lat: 34.8315, lng: 74.0601 }, amenities: ['Camping', 'Horses'], reviews: 140 },
  { id: '24', name: 'Arang Kel', region: 'Azad Kashmir', description: 'The Pearl of Neelum Valley.', imageUrl: 'https://picsum.photos/id/188/800/600', tags: ['hiking', 'view'], rating: 4.8, coordinates: { lat: 34.8080, lng: 74.3486 }, amenities: ['Huts'], reviews: 110 },
  { id: '25', name: 'Pir Chinasi', region: 'Azad Kashmir', description: 'Tourist spot known for its breathtaking views of Muzaffarabad.', imageUrl: 'https://picsum.photos/id/190/800/600', tags: ['viewpoint', 'shrine'], rating: 4.5, coordinates: { lat: 34.3934, lng: 73.5516 }, amenities: ['Paragliding'], reviews: 100 },
  { id: '26', name: 'Banjosa Lake', region: 'Azad Kashmir', description: 'Artificial lake and tourist resort near Rawalakot.', imageUrl: 'https://picsum.photos/id/192/800/600', tags: ['picnic', 'lake'], rating: 4.4, coordinates: { lat: 33.8099, lng: 73.8166 }, amenities: ['Boating'], reviews: 150 },

  // Punjab
  { id: '30', name: 'Lahore Fort', region: 'Punjab', description: 'Citadel of the city of Lahore, a UNESCO World Heritage Site.', imageUrl: 'https://picsum.photos/id/200/800/600', tags: ['history', 'architecture', 'mughal'], rating: 4.8, coordinates: { lat: 31.5880, lng: 74.3152 }, amenities: ['Museum', 'Guides'], reviews: 500 },
  { id: '31', name: 'Badshahi Mosque', region: 'Punjab', description: 'One of the largest mosques in the world, built by Aurangzeb.', imageUrl: 'https://picsum.photos/id/201/800/600', tags: ['history', 'religious', 'architecture'], rating: 4.9, coordinates: { lat: 31.5881, lng: 74.3095 }, amenities: ['Prayer Hall', 'Museum'], reviews: 600 },
  { id: '32', name: 'Shalimar Gardens', region: 'Punjab', description: 'Mughal garden complex located in Lahore.', imageUrl: 'https://picsum.photos/id/202/800/600', tags: ['nature', 'history', 'garden'], rating: 4.5, coordinates: { lat: 31.5857, lng: 74.3818 }, amenities: ['Walking Tracks'], reviews: 200 },
  { id: '33', name: 'Walled City of Lahore', region: 'Punjab', description: 'The historic core of Lahore with narrow streets and culture.', imageUrl: 'https://picsum.photos/id/203/800/600', tags: ['culture', 'food', 'walking'], rating: 4.7, coordinates: { lat: 31.5882, lng: 74.3160 }, amenities: ['Food Street', 'Guides'], reviews: 400 },
  { id: '34', name: 'Minar-e-Pakistan', region: 'Punjab', description: 'Public monument located in Iqbal Park, Lahore.', imageUrl: 'https://picsum.photos/id/204/800/600', tags: ['history', 'monument'], rating: 4.6, coordinates: { lat: 31.5925, lng: 74.3095 }, amenities: ['Park'], reviews: 300 },
  { id: '35', name: 'Derawar Fort', region: 'Punjab', description: 'Large square fortress in Ahmedpur East.', imageUrl: 'https://picsum.photos/id/206/800/600', tags: ['desert', 'history', 'fort'], rating: 4.5, coordinates: { lat: 28.7680, lng: 71.3338 }, amenities: ['Camel Ride'], reviews: 100 },
  { id: '36', name: 'Katas Raj Temples', region: 'Punjab', description: 'Complex of several Hindu temples connected to one another by walkways.', imageUrl: 'https://picsum.photos/id/208/800/600', tags: ['history', 'religious'], rating: 4.6, coordinates: { lat: 32.7275, lng: 72.9567 }, amenities: ['Guides'], reviews: 90 },
  { id: '37', name: 'Rohtas Fort', region: 'Punjab', description: '16th-century fortress located near the city of Jhelum.', imageUrl: 'https://picsum.photos/id/209/800/600', tags: ['history', 'fort', 'architecture'], rating: 4.7, coordinates: { lat: 32.9649, lng: 73.5776 }, amenities: ['Museum'], reviews: 110 },
  { id: '38', name: 'Khewra Salt Mine', region: 'Punjab', description: 'Second largest salt mine in the world.', imageUrl: 'https://picsum.photos/id/210/800/600', tags: ['mining', 'tourist'], rating: 4.4, coordinates: { lat: 32.6469, lng: 73.0075 }, amenities: ['Train Ride', 'Souvenirs'], reviews: 250 },
  { id: '39', name: 'Noor Mahal', region: 'Punjab', description: 'Italian chateau-style palace in Bahawalpur.', imageUrl: 'https://picsum.photos/id/211/800/600', tags: ['history', 'palace', 'luxury'], rating: 4.7, coordinates: { lat: 29.3949, lng: 71.6669 }, amenities: ['Light Show', 'Museum'], reviews: 140 },
  { id: '40', name: 'Tomb of Jahangir', region: 'Punjab', description: 'Mausoleum built for the Mughal Emperor Jahangir.', imageUrl: 'https://picsum.photos/id/212/800/600', tags: ['history', 'architecture'], rating: 4.6, coordinates: { lat: 31.6214, lng: 74.2982 }, amenities: ['Gardens'], reviews: 160 },
  
  // Sindh
  { id: '50', name: 'Mohenjo-daro', region: 'Sindh', description: 'Archaeological site in the province of Sindh, settlement of the Indus Valley Civilization.', imageUrl: 'https://picsum.photos/id/220/800/600', tags: ['history', 'ancient', 'archaeology'], rating: 4.7, coordinates: { lat: 27.3292, lng: 68.1386 }, amenities: ['Museum', 'Guides'], reviews: 180 },
  { id: '51', name: 'Makli Necropolis', region: 'Sindh', description: 'One of the largest funerary sites in the world.', imageUrl: 'https://picsum.photos/id/221/800/600', tags: ['history', 'graveyard', 'unesco'], rating: 4.6, coordinates: { lat: 24.7471, lng: 67.8929 }, amenities: ['Guides'], reviews: 80 },
  { id: '52', name: 'Clifton Beach', region: 'Sindh', description: 'Popular beach in Karachi.', imageUrl: 'https://picsum.photos/id/222/800/600', tags: ['beach', 'city', 'food'], rating: 4.0, coordinates: { lat: 24.8080, lng: 67.0270 }, amenities: ['Camel Rides', 'Restaurants'], reviews: 500 },
  { id: '53', name: 'Mazar-e-Quaid', region: 'Sindh', description: 'Final resting place of Quaid-e-Azam Muhammad Ali Jinnah.', imageUrl: 'https://picsum.photos/id/223/800/600', tags: ['history', 'monument'], rating: 4.8, coordinates: { lat: 24.8728, lng: 67.0425 }, amenities: ['Park', 'Museum'], reviews: 400 },
  { id: '54', name: 'Ranikot Fort', region: 'Sindh', description: 'Also known as The Great Wall of Sindh.', imageUrl: 'https://picsum.photos/id/225/800/600', tags: ['fort', 'history', 'trekking'], rating: 4.5, coordinates: { lat: 25.8860, lng: 67.8928 }, amenities: ['Camping'], reviews: 60 },
  { id: '55', name: 'Gorakh Hill', region: 'Sindh', description: 'Hill station of Sindh, known as the Murree of Sindh.', imageUrl: 'https://picsum.photos/id/227/800/600', tags: ['hill station', 'cold', 'adventure'], rating: 4.3, coordinates: { lat: 26.8364, lng: 67.1472 }, amenities: ['Resort', 'Jeep Ride'], reviews: 120 },
  { id: '56', name: 'Keenjhar Lake', region: 'Sindh', description: 'Second largest fresh water lake in Pakistan.', imageUrl: 'https://picsum.photos/id/229/800/600', tags: ['lake', 'picnic', 'legend'], rating: 4.2, coordinates: { lat: 24.9450, lng: 68.0464 }, amenities: ['Boating', 'Huts'], reviews: 150 },
  { id: '57', name: 'Empress Market', region: 'Sindh', description: 'Historic marketplace in Karachi.', imageUrl: 'https://picsum.photos/id/230/800/600', tags: ['shopping', 'history', 'british'], rating: 4.4, coordinates: { lat: 24.8623, lng: 67.0277 }, amenities: ['Shops'], reviews: 300 },
  { id: '58', name: 'Chaukhandi Tombs', region: 'Sindh', description: 'Ancient graveyard known for intricate sandstone carvings.', imageUrl: 'https://picsum.photos/id/231/800/600', tags: ['history', 'art'], rating: 4.5, coordinates: { lat: 24.8710, lng: 67.2627 }, amenities: ['Guide'], reviews: 50 },
  { id: '59', name: 'French Beach', region: 'Sindh', description: 'Exclusive beach near Karachi with huts.', imageUrl: 'https://picsum.photos/id/235/800/600', tags: ['beach', 'swimming', 'private'], rating: 4.6, coordinates: { lat: 24.8465, lng: 66.9029 }, amenities: ['Huts', 'Privacy'], reviews: 100 },

  // Balochistan
  { id: '70', name: 'Gwadar Port', region: 'Balochistan', description: 'Deep sea port known for its strategic importance and beautiful beaches.', imageUrl: 'https://picsum.photos/id/240/800/600', tags: ['coastal', 'development', 'beach'], rating: 4.5, coordinates: { lat: 25.1264, lng: 62.3225 }, amenities: ['Hotels', 'Fish Market'], reviews: 110 },
  { id: '71', name: 'Princess of Hope', region: 'Balochistan', description: 'Natural rock formation in Hingol National Park.', imageUrl: 'https://picsum.photos/id/241/800/600', tags: ['nature', 'rock', 'art'], rating: 4.6, coordinates: { lat: 25.4326, lng: 65.5256 }, amenities: ['Viewpoint'], reviews: 130 },
  { id: '72', name: 'Hingol National Park', region: 'Balochistan', description: 'Largest national park in Pakistan.', imageUrl: 'https://picsum.photos/id/242/800/600', tags: ['wildlife', 'nature', 'desert'], rating: 4.7, coordinates: { lat: 25.5434, lng: 65.5390 }, amenities: ['Safari'], reviews: 90 },
  { id: '73', name: 'Kund Malir Beach', region: 'Balochistan', description: 'Pristine beach located in Hingol National Park.', imageUrl: 'https://picsum.photos/id/243/800/600', tags: ['beach', 'nature', 'clean'], rating: 4.8, coordinates: { lat: 25.3934, lng: 65.4650 }, amenities: ['Huts', 'Camping'], reviews: 200 },
  { id: '74', name: 'Ziarat', region: 'Balochistan', description: 'Home to the second largest juniper forest in the world and Quaid\'s residency.', imageUrl: 'https://picsum.photos/id/244/800/600', tags: ['nature', 'history', 'cold'], rating: 4.6, coordinates: { lat: 30.3824, lng: 67.7256 }, amenities: ['Residency', 'Hotels'], reviews: 140 },
  { id: '75', name: 'Moola Chotok', region: 'Balochistan', description: 'Hidden oasis with waterfalls in Khuzdar.', imageUrl: 'https://picsum.photos/id/245/800/600', tags: ['adventure', 'waterfall', 'oasis'], rating: 4.8, coordinates: { lat: 28.1634, lng: 67.1471 }, amenities: ['Camping', '4x4 Required'], reviews: 80 },
  { id: '76', name: 'Astola Island', region: 'Balochistan', description: 'Known as Island of the Seven Hills, a remote camping spot.', imageUrl: 'https://picsum.photos/id/246/800/600', tags: ['adventure', 'island', 'camping'], rating: 4.9, coordinates: { lat: 25.1219, lng: 63.8488 }, amenities: ['Boat Ride', 'No Facilities'], reviews: 60 },
  { id: '77', name: 'Hanna Lake', region: 'Balochistan', description: 'Lake near Quetta, popular for picnics.', imageUrl: 'https://picsum.photos/id/247/800/600', tags: ['lake', 'picnic'], rating: 4.3, coordinates: { lat: 30.2520, lng: 67.1009 }, amenities: ['Boating', 'Restaurant'], reviews: 150 },
  { id: '78', name: 'Pir Ghaib Falls', region: 'Balochistan', description: 'Waterfalls and palm trees in the middle of the desert.', imageUrl: 'https://picsum.photos/id/248/800/600', tags: ['oasis', 'waterfall'], rating: 4.5, coordinates: { lat: 29.7431, lng: 67.5925 }, amenities: ['Swimming'], reviews: 50 },
];

export const HOTELS: Hotel[] = [
  { id: 'h1', name: 'Serena Hotel Islamabad', location: 'Islamabad', pricePerNight: 45000, rating: 4.9, imageUrl: 'https://picsum.photos/id/1050/400/300', amenities: ['Pool', 'Spa', '5-Star'] },
  { id: 'h2', name: 'Luxus Grand', location: 'Lahore', pricePerNight: 20000, rating: 4.6, imageUrl: 'https://picsum.photos/id/1051/400/300', amenities: ['Gym', 'Breakfast'] },
  { id: 'h3', name: 'Pearl Continental', location: 'Bhurban', pricePerNight: 35000, rating: 4.7, imageUrl: 'https://picsum.photos/id/1052/400/300', amenities: ['Mountain View', 'Golf'] },
  { id: 'h4', name: 'Shangrila Resort', location: 'Skardu', pricePerNight: 40000, rating: 4.8, imageUrl: 'https://picsum.photos/id/1053/400/300', amenities: ['Lake View', 'Boating'] },
  { id: 'h5', name: 'Darbar Hotel', location: 'Hunza', pricePerNight: 15000, rating: 4.5, imageUrl: 'https://picsum.photos/id/1054/400/300', amenities: ['View', 'Traditional Food'] },
  { id: 'h6', name: 'Zaver Pearl', location: 'Gwadar', pricePerNight: 18000, rating: 4.4, imageUrl: 'https://picsum.photos/id/1055/400/300', amenities: ['Sea View', 'Business Center'] },
];

export const CARS: Car[] = [
  { id: 'c1', model: 'Toyota Prado', type: '4x4', pricePerDay: 15000, imageUrl: 'https://picsum.photos/id/1070/400/300', features: ['AC', 'Off-road', '7 Seats'] },
  { id: 'c2', model: 'Honda Civic', type: 'Sedan', pricePerDay: 8000, imageUrl: 'https://picsum.photos/id/1071/400/300', features: ['AC', 'Auto', 'Comfort'] },
  { id: 'c3', model: 'Toyota HiAce', type: 'Van', pricePerDay: 12000, imageUrl: 'https://picsum.photos/id/1072/400/300', features: ['12 Seats', 'AC', 'Tour Group'] },
  { id: 'c4', model: 'Suzuki Alto', type: 'Sedan', pricePerDay: 4000, imageUrl: 'https://picsum.photos/id/1073/400/300', features: ['Economy', 'City'] },
  { id: 'c5', model: 'Toyota Fortuner', type: 'SUV', pricePerDay: 18000, imageUrl: 'https://picsum.photos/id/1074/400/300', features: ['Luxury', 'Off-road'] },
];

export const RECOMMENDATIONS_TEMPLATE = [
  { title: "Northern Adventure", tags: ["mountains", "trekking", "lake"], days: 7, budget: "standard" },
  { title: "Coastal Retreat", tags: ["beach", "sea", "relax"], days: 3, budget: "luxury" },
  { title: "Heritage Walk", tags: ["history", "fort", "culture"], days: 2, budget: "budget" }
];
